// <auto-generated />
using System;
using GoalKeeper.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoalKeeper.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GoalKeeperDbContext))]
    [Migration("20260717040651_InitialPhaseTwo")]
    partial class InitialPhaseTwo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("GoalKeeper.Infrastructure.ApplicationSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("ApplicationSettings", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.AuditEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromState")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SessionVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToState")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.ContractBreakEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ActiveFocusOffsetTicks")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractBreaks", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.ContractDeviationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractDeviations", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.ContractEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ConfirmedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviationProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviationProfileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoalDescription")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoalTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TargetFocusTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("SessionContracts", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.DeviationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Deviations", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.DeviationOverrideEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ListedDeviationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnlistedDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeviationOverrides", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.DeviationProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DeviationProfiles", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.EvidenceEpisodeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ListedDeviationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnlistedDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EvidenceEpisodes", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.FocusSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AccumulatedFocusTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtifactDirectory")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.HasIndex("GoalId");

                    b.ToTable("FocusSessions", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.GoalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Goals", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.InterventionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AdmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DisputedTicks")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvidenceEpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Interventions", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.ObservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId")
                        .IsUnique();

                    b.ToTable("Observations", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.ReasoningEvaluationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EvaluatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SessionVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ReasoningEvaluations", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.RecoveryTurnEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InterventionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transcript")
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RecoveryTurns", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.SessionReviewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Helpfulness")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MarkGoalComplete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MeaningfulProgress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("SessionReviews", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.SessionSetupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.ToTable("SessionSetups", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.SnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SessionVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StoredBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("Snapshots", (string)null);
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.ContractBreakEntity", b =>
                {
                    b.HasOne("GoalKeeper.Infrastructure.ContractEntity", "Contract")
                        .WithMany("Breaks")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.ContractDeviationEntity", b =>
                {
                    b.HasOne("GoalKeeper.Infrastructure.ContractEntity", "Contract")
                        .WithMany("Deviations")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.ContractEntity", b =>
                {
                    b.HasOne("GoalKeeper.Infrastructure.GoalEntity", "Goal")
                        .WithMany("Contracts")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.DeviationEntity", b =>
                {
                    b.HasOne("GoalKeeper.Infrastructure.DeviationProfileEntity", "Profile")
                        .WithMany("Deviations")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.FocusSessionEntity", b =>
                {
                    b.HasOne("GoalKeeper.Infrastructure.ContractEntity", "Contract")
                        .WithOne()
                        .HasForeignKey("GoalKeeper.Infrastructure.FocusSessionEntity", "ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoalKeeper.Infrastructure.GoalEntity", "Goal")
                        .WithMany("Sessions")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.SessionSetupEntity", b =>
                {
                    b.HasOne("GoalKeeper.Infrastructure.ContractEntity", "Contract")
                        .WithOne("Setup")
                        .HasForeignKey("GoalKeeper.Infrastructure.SessionSetupEntity", "ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.SnapshotEntity", b =>
                {
                    b.HasOne("GoalKeeper.Infrastructure.FocusSessionEntity", "Session")
                        .WithMany("Snapshots")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.ContractEntity", b =>
                {
                    b.Navigation("Breaks");

                    b.Navigation("Deviations");

                    b.Navigation("Setup");
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.DeviationProfileEntity", b =>
                {
                    b.Navigation("Deviations");
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.FocusSessionEntity", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("GoalKeeper.Infrastructure.GoalEntity", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
